include_guard(GLOBAL)

# cortex_flags(<profile> <out_var>) -> sets <out_var> in the caller's scope
function(cortex_flags PROFILE OUT_VAR)
    if(PROFILE STREQUAL "cortex-m0")
        set(f -mcpu=cortex-m0     -mfloat-abi=soft)
    elseif(PROFILE STREQUAL "cortex-m0plus")
        set(f -mcpu=cortex-m0plus -mfloat-abi=soft)
    elseif(PROFILE STREQUAL "cortex-m3")
        set(f -mcpu=cortex-m3     -mfloat-abi=soft)
    elseif(PROFILE STREQUAL "cortex-m4")
        set(f -mcpu=cortex-m4     -mfloat-abi=soft)
    elseif(PROFILE STREQUAL "cortex-m4f")
        set(f -mcpu=cortex-m4  -mfpu=fpv4-sp-d16 -mfloat-abi=hard)
    elseif(PROFILE STREQUAL "cortex-m7f")
        set(f -mcpu=cortex-m7  -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    elseif(PROFILE STREQUAL "cortex-m7d")
        set(f -mcpu=cortex-m7  -mfpu=fpv5-d16    -mfloat-abi=hard)
    elseif(PROFILE STREQUAL "cortex-m33f")
        set(f -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard)
    else()
        message(FATAL_ERROR "Unknown CPU_PROFILE '${PROFILE}'. Known: cortex-m0, cortex-m0plus, "
                            "cortex-m3, cortex-m4, cortex-m4f, cortex-m7f, cortex-m7d, cortex-m33f")
    endif()
    set(${OUT_VAR} ${f} -mthumb PARENT_SCOPE)
endfunction()
