function(add_stm32_board BOARD_DIR BOARD_NAME TARGET_MCU)
    # Define compiler flags for the target MCU
    # STM32F401RETx uses cortex-m4, fpv4-sp-d16
    set(TARGET_FLAGS -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb)
    
    # We will create an interface library for the STM32 board configuration
    # This allows APPS to easily inherit all include paths and definitions
    add_library(${BOARD_NAME}_config INTERFACE)
    
    # Add include directories from CubeIDE project structure
    target_include_directories(${BOARD_NAME}_config INTERFACE
        ${BOARD_DIR}/Core/Inc
        ${BOARD_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc
        ${BOARD_DIR}/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy
        ${BOARD_DIR}/Drivers/CMSIS/Device/ST/STM32F4xx/Include
        ${BOARD_DIR}/Drivers/CMSIS/Include
    )
    
    # Add definitions generated by CubeMX
    target_compile_definitions(${BOARD_NAME}_config INTERFACE
        USE_FULL_LL_DRIVER
        ${TARGET_MCU}
    )
    
    # Add target flags
    target_compile_options(${BOARD_NAME}_config INTERFACE ${TARGET_FLAGS})
    target_link_options(${BOARD_NAME}_config INTERFACE ${TARGET_FLAGS})
    
    # Glob the source files from the STM32CubeIDE project
    file(GLOB_RECURSE STM32_SOURCES
        "${BOARD_DIR}/Core/Src/*.c"
        "${BOARD_DIR}/Drivers/STM32F4xx_HAL_Driver/Src/*.c"
    )
    
    # Glob startup script (.s)
    file(GLOB STM32_STARTUP "${BOARD_DIR}/Core/Startup/*.s")
    
    # Create the executable for the board
    add_executable(${BOARD_NAME} ${STM32_SOURCES} ${STM32_STARTUP})
    
    # Link it to the configuration
    target_link_libraries(${BOARD_NAME} PRIVATE ${BOARD_NAME}_config)
    
    # Find the linker script in the board directory
    file(GLOB STM32_LINKER_SCRIPT "${BOARD_DIR}/*FLASH.ld")
    if (STM32_LINKER_SCRIPT)
        # Assuming only one FLASH.ld is found
        list(GET STM32_LINKER_SCRIPT 0 LINKER_SCRIPT)
        target_link_options(${BOARD_NAME} PRIVATE
            -T${LINKER_SCRIPT}
            --specs=nano.specs
            -Wl,-Map=${CMAKE_PROJECT_NAME}.map
            -Wl,--gc-sections
            -Wl,--print-memory-usage
        )
    else()
        message(FATAL_ERROR "Could not find a FLASH.ld linker script in ${BOARD_DIR}")
    endif()
    
    # Add math library
    target_link_libraries(${BOARD_NAME} PRIVATE m)
    
endfunction()
